name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test-ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      #- run: npm run test (to-do create unittest)

  deploy:
    needs: test-ci
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run build
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: your-docker-registry/vuejs-tree-map:latest
      - name: Deploy to production
        run: |
          # to-do
